WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1086698510
MERGE-OUTER: 61 files, 0 in the initial corpus, 0 processed earlier
MERGE-OUTER: attempt 1
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1086710648
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: 61 total files; 0 processed earlier; will process 61 files now
[2022-11-05T00:27:18Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/execute.options"
[2022-11-05T00:27:18Z DEBUG fvm_fuzz] Preseed 0
[2022-11-05T00:27:18Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:27:18Z DEBUG fvm_fuzz] Seed: 8100708189767581495
[2022-11-05T00:27:18Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:27:18Z DEBUG fvm_fuzz] Seed: 18075600217600495122
[2022-11-05T00:27:18Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:27:18Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:27:35Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacebfnp4lbbzzhmlbirjzumrngpdg4awedpufzvbondu5vx5ro2kz4w

Caused by:
    0: failed to validate actor wasm
    1: magic header not detected: bad magic number (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==191== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0xcb,
\313
artifact_prefix='./'; Test unit written to ./crash-12bdd00fd4038756cbcf8ecdad1b0cd862603cd8
Base64: yw==
MERGE-OUTER: attempt 2
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1104348666
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/12bdd00fd4038756cbcf8ecdad1b0cd862603cd8' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 1 processed earlier; will process 60 files now
[2022-11-05T00:27:36Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/execute.options"
[2022-11-05T00:27:36Z DEBUG fvm_fuzz] Preseed 0
[2022-11-05T00:27:36Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:27:36Z DEBUG fvm_fuzz] Seed: 8100708189767581495
[2022-11-05T00:27:36Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:27:36Z DEBUG fvm_fuzz] Seed: 18075600217600495122
[2022-11-05T00:27:36Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:27:36Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:27:50Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacebfnp4lbbzzhmlbirjzumrngpdg4awedpufzvbondu5vx5ro2kz4w

Caused by:
    0: failed to validate actor wasm
    1: magic header not detected: bad magic number (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==219== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0xca,
\312
artifact_prefix='./'; Test unit written to ./crash-7ef8aa6a336b4a7122031d713f383ffbbe5fac93
Base64: yg==
MERGE-OUTER: attempt 3
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1119149949
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/7ef8aa6a336b4a7122031d713f383ffbbe5fac93' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 2 processed earlier; will process 59 files now
[2022-11-05T00:27:51Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-9a78211436f6d425ec38f5c4e02270801f3524f8"
[2022-11-05T00:27:51Z DEBUG fvm_fuzz] Preseed 0
[2022-11-05T00:27:51Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:27:51Z DEBUG fvm_fuzz] Seed: 8100708189767581495
[2022-11-05T00:27:51Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:27:51Z DEBUG fvm_fuzz] Seed: 18075600217600495122
[2022-11-05T00:27:51Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:27:51Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:28:04Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacea456askyutsf7uk4ta2q5aojrlcji4mhaqokbfalgvoq4ueeh4l2

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==283== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x31,
1
artifact_prefix='./'; Test unit written to ./crash-356a192b7913b04c54574d18c28d46e6395428ab
Base64: MQ==
MERGE-OUTER: attempt 4
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1133091775
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/356a192b7913b04c54574d18c28d46e6395428ab' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 3 processed earlier; will process 58 files now
[2022-11-05T00:28:05Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-5d1be7e9dda1ee8896be5b7e34a85ee16452a7b4"
[2022-11-05T00:28:05Z DEBUG fvm_fuzz] Preseed 0
[2022-11-05T00:28:05Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:28:05Z DEBUG fvm_fuzz] Seed: 8100708189767581495
[2022-11-05T00:28:05Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:28:05Z DEBUG fvm_fuzz] Seed: 18075600217600495122
[2022-11-05T00:28:05Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:28:05Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:28:16Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacecdt4t7j4qpjesirxor6yu77i6bo7sga6jcpw5oiph4kimunafbmu

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==301== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0xea,
\352
artifact_prefix='./'; Test unit written to ./crash-3c89586d99f2567d21410f29b1b2606574892aa7
Base64: 6g==
MERGE-OUTER: attempt 5
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1144564581
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/3c89586d99f2567d21410f29b1b2606574892aa7' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 4 processed earlier; will process 57 files now
[2022-11-05T00:28:16Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-fb96549631c835eb239cd614cc6b5cb7d295121a"
[2022-11-05T00:28:16Z DEBUG fvm_fuzz] Preseed 0
[2022-11-05T00:28:16Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:28:16Z DEBUG fvm_fuzz] Seed: 8100708189767581495
[2022-11-05T00:28:16Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:28:16Z DEBUG fvm_fuzz] Seed: 18075600217600495122
[2022-11-05T00:28:16Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:28:16Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:28:27Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedf4mpocvs4gxweworj67gh5j4v6f4tnom32be3zlaqryeukdc2ee

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==346== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x2a,
*
artifact_prefix='./'; Test unit written to ./crash-df58248c414f342c81e056b40bee12d17a08bf61
Base64: Kg==
MERGE-OUTER: attempt 6
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1156063644
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/df58248c414f342c81e056b40bee12d17a08bf61' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 5 processed earlier; will process 56 files now
[2022-11-05T00:28:28Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-3cf7b6eb05c07ef15b2c1de6fc7dffe1d8d62b72"
[2022-11-05T00:28:28Z DEBUG fvm_fuzz] Preseed 0
[2022-11-05T00:28:28Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:28:28Z DEBUG fvm_fuzz] Seed: 8100708189767581495
[2022-11-05T00:28:28Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:28:28Z DEBUG fvm_fuzz] Seed: 18075600217600495122
[2022-11-05T00:28:28Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:28:28Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:28:38Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedo7alatkt4wp6pjrjg2olufeeesltqru6bbunmzclvdunrm5mwda

Caused by:
    0: failed to validate actor wasm
    1: magic header not detected: bad magic number (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==394== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x37,
7
artifact_prefix='./'; Test unit written to ./crash-902ba3cda1883801594b6e1b452790cc53948fda
Base64: Nw==
MERGE-OUTER: attempt 7
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1167405137
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/902ba3cda1883801594b6e1b452790cc53948fda' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 6 processed earlier; will process 55 files now
[2022-11-05T00:28:39Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/execute"
[2022-11-05T00:28:40Z DEBUG fvm_fuzz] Preseed 0
[2022-11-05T00:28:40Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:28:40Z DEBUG fvm_fuzz] Seed: 8100708189767581495
[2022-11-05T00:28:40Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:28:40Z DEBUG fvm_fuzz] Seed: 18075600217600495122
[2022-11-05T00:28:41Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:28:41Z DEBUG fvm_fuzz] Executing 50 times
==400== ERROR: libFuzzer: out-of-memory (used: 2169Mb; limit: 2048Mb)
   To change the out-of-memory limit use -rss_limit_mb=<N>

MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x32,
2
artifact_prefix='./'; Test unit written to ./oom-da4b9237bacccdf19c0760cab7aec4a8359010b0
Base64: Mg==
SUMMARY: libFuzzer: out-of-memory
MERGE-OUTER: attempt 8
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1169424372
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/da4b9237bacccdf19c0760cab7aec4a8359010b0' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 7 processed earlier; will process 54 files now
[2022-11-05T00:28:41Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-2756a5b3f42e364c198815f2bdd7d89bf0cacce4"
[2022-11-05T00:28:41Z DEBUG fvm_fuzz] Preseed 0
[2022-11-05T00:28:41Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:28:41Z DEBUG fvm_fuzz] Seed: 8100708189767581495
[2022-11-05T00:28:41Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(1) } }) }
[2022-11-05T00:28:41Z DEBUG fvm_fuzz] Seed: 18075600217600495122
[2022-11-05T00:28:41Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(1) } }) }
[2022-11-05T00:28:41Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:28:52Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedbvmcemvfgntl5pbx6wf4exm3nrdp7qagk5bpls32qigiucknuzu

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==403== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x90,
\220
artifact_prefix='./'; Test unit written to ./crash-c4595d8f743731cbc1ca0bb34be79a40d771ddf0
Base64: kA==
MERGE-OUTER: attempt 9
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1180754222
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/c4595d8f743731cbc1ca0bb34be79a40d771ddf0' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 8 processed earlier; will process 53 files now
[2022-11-05T00:28:52Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/llvm-symbolizer"
[2022-11-05T00:28:52Z DEBUG fvm_fuzz] Preseed 0
[2022-11-05T00:28:52Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:28:52Z DEBUG fvm_fuzz] Seed: 8100708189767581495
[2022-11-05T00:28:52Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:28:52Z DEBUG fvm_fuzz] Seed: 18075600217600495122
[2022-11-05T00:28:52Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:28:52Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:29:04Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedxuacqpkd2rovquf5r2tlnhrculv4mp3qlerkyju46fycn6wmruw

Caused by:
    0: failed to validate actor wasm
    1: magic header not detected: bad magic number (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==406== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0xa,
\012
artifact_prefix='./'; Test unit written to ./crash-adc83b19e793491b1c6ea0fd8b46cd9f32e592fc
Base64: Cg==
MERGE-OUTER: attempt 10
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1192612974
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/adc83b19e793491b1c6ea0fd8b46cd9f32e592fc' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 9 processed earlier; will process 52 files now
[2022-11-05T00:29:04Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/dummy_corpus_dir_for_execute"
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 21, kind: IsADirectory, message: "Is a directory" })', fuzz/fuzz_targets/execute.rs:34:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==409== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0xb,
\013
artifact_prefix='./'; Test unit written to ./crash-067d5096f219c64b53bb1c7d5e3754285b565a47
Base64: Cw==
MERGE-OUTER: attempt 11
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1192626415
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/067d5096f219c64b53bb1c7d5e3754285b565a47' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 10 processed earlier; will process 51 files now
[2022-11-05T00:29:04Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-2830db7726582010627cc5481329b73487cf9e91"
[2022-11-05T00:29:04Z DEBUG fvm_fuzz] Preseed 0
[2022-11-05T00:29:04Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:29:04Z DEBUG fvm_fuzz] Seed: 8100708189767581495
[2022-11-05T00:29:04Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:29:04Z DEBUG fvm_fuzz] Seed: 18075600217600495122
[2022-11-05T00:29:04Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:29:04Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:29:15Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacecre7og7qruvyupldmgtfrugihznik2xq4ntupuwobv5kwbe2slfe

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==412== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x24,
$
artifact_prefix='./'; Test unit written to ./crash-3cdf2936da2fc556bfa533ab1eb59ce710ac80e5
Base64: JA==
MERGE-OUTER: attempt 12
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1203960558
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/3cdf2936da2fc556bfa533ab1eb59ce710ac80e5' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 11 processed earlier; will process 50 files now
[2022-11-05T00:29:15Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-2457e0750cd473513c3a61ff39699df1fc668609"
[2022-11-05T00:29:15Z DEBUG fvm_fuzz] Preseed 0
[2022-11-05T00:29:15Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:29:15Z DEBUG fvm_fuzz] Seed: 8100708189767581495
[2022-11-05T00:29:15Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:29:15Z DEBUG fvm_fuzz] Seed: 18075600217600495122
[2022-11-05T00:29:15Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:29:15Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:29:26Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzaceadrt6luthkoftjkswkiwipripq4g5my3izikt7pz45bjlvcgeujs

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==415== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x4a,
J
artifact_prefix='./'; Test unit written to ./crash-58668e7669fd564d99db5d581fcdb6a5618440b5
Base64: Sg==
MERGE-OUTER: attempt 13
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1215296841
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/58668e7669fd564d99db5d581fcdb6a5618440b5' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 12 processed earlier; will process 49 files now
[2022-11-05T00:29:27Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-2386e77cf610f786b06a91af2c1b3fd2282d2745"
[2022-11-05T00:29:27Z DEBUG fvm_fuzz] Preseed 0
[2022-11-05T00:29:27Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:29:27Z DEBUG fvm_fuzz] Seed: 8100708189767581495
[2022-11-05T00:29:27Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:29:27Z DEBUG fvm_fuzz] Seed: 18075600217600495122
[2022-11-05T00:29:27Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:29:27Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:29:38Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzaceay5uxowaw5lw5kzm7jg4dxt7guk7rbhwoowyfeouzsvva5dq4wbu

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==418== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x8a,
\212
artifact_prefix='./'; Test unit written to ./crash-c4488af0c158e8c2832cb927cfb3ce534104cd1e
Base64: ig==
MERGE-OUTER: attempt 14
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1226691429
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/c4488af0c158e8c2832cb927cfb3ce534104cd1e' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 13 processed earlier; will process 48 files now
[2022-11-05T00:29:38Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-da04fff1aca2a093f4000025e853d597b15ac691"
[2022-11-05T00:29:38Z DEBUG fvm_fuzz] Preseed 0
[2022-11-05T00:29:38Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:29:38Z DEBUG fvm_fuzz] Seed: 8100708189767581495
[2022-11-05T00:29:38Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:29:38Z DEBUG fvm_fuzz] Seed: 18075600217600495122
[2022-11-05T00:29:38Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:29:38Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:29:49Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacectgftgwjmjn22hl2ifomg2ptovli4a6b65aiwibyakd5kssiv4xy

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==421== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0xaa,
\252
artifact_prefix='./'; Test unit written to ./crash-52538a80094f7b62948fd31e68fd17a315d8dc91
Base64: qg==
MERGE-OUTER: attempt 15
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1238073612
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/52538a80094f7b62948fd31e68fd17a315d8dc91' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 14 processed earlier; will process 47 files now
[2022-11-05T00:29:50Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-7219e685eebe2b43caf431c16ba90a1f6ffc0b16"
[2022-11-05T00:29:50Z DEBUG fvm_fuzz] Preseed 0
[2022-11-05T00:29:50Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:29:50Z DEBUG fvm_fuzz] Seed: 8100708189767581495
[2022-11-05T00:29:50Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:29:50Z DEBUG fvm_fuzz] Seed: 18075600217600495122
[2022-11-05T00:29:50Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:29:50Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:30:01Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacecporvtv5gsbjdgs4wllb2h6fwqdjf4lltbknescr2bh77evts6y2

Caused by:
    0: failed to validate actor wasm
    1: magic header not detected: bad magic number (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==424== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x36,
6
artifact_prefix='./'; Test unit written to ./crash-c1dfd96eea8cc2b62785275bca38ac261256e278
Base64: Ng==
MERGE-OUTER: attempt 16
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1249461170
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/c1dfd96eea8cc2b62785275bca38ac261256e278' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 15 processed earlier; will process 46 files now
[2022-11-05T00:30:01Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-e5af0f70923b1a0db383315803c318bb533d0635"
[2022-11-05T00:30:01Z DEBUG fvm_fuzz] Preseed 0
[2022-11-05T00:30:01Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:30:01Z DEBUG fvm_fuzz] Seed: 8100708189767581495
[2022-11-05T00:30:01Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:30:01Z DEBUG fvm_fuzz] Seed: 18075600217600495122
[2022-11-05T00:30:01Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:30:01Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:30:12Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacecqyl445pqzyoz47q72k2nx6zd2dyzewteamhkw7oh6vol3r7kwf2

Caused by:
    0: failed to validate actor wasm
    1: magic header not detected: bad magic number (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==427== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x40,
@
artifact_prefix='./'; Test unit written to ./crash-9a78211436f6d425ec38f5c4e02270801f3524f8
Base64: QA==
MERGE-OUTER: attempt 17
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1260814203
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/9a78211436f6d425ec38f5c4e02270801f3524f8' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 16 processed earlier; will process 45 files now
[2022-11-05T00:30:12Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-6a2ffa3567b0d286348f4e6942d3e8e62d820d2a"
[2022-11-05T00:30:12Z DEBUG fvm_fuzz] Preseed 0
[2022-11-05T00:30:12Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:30:12Z DEBUG fvm_fuzz] Seed: 8100708189767581495
[2022-11-05T00:30:12Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:30:12Z DEBUG fvm_fuzz] Seed: 18075600217600495122
[2022-11-05T00:30:12Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:30:12Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:30:23Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzaced2ceh23j2mfvnuftyj6wvjsj5mxkjeuzqugmy5ii7nxycstrg6j6

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==430== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x5b,
[
artifact_prefix='./'; Test unit written to ./crash-1e5c2f367f02e47a8c160cda1cd9d91decbac441
Base64: Ww==
MERGE-OUTER: attempt 18
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1272169884
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/1e5c2f367f02e47a8c160cda1cd9d91decbac441' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 17 processed earlier; will process 44 files now
[2022-11-05T00:30:24Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-2756a5b3f42e364c198815f2bdd7d89bf0cacce4"
[2022-11-05T00:30:24Z DEBUG fvm_fuzz] Preseed 36
[2022-11-05T00:30:24Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:30:24Z DEBUG fvm_fuzz] Seed: 8233762969215426441
[2022-11-05T00:30:24Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(1) } }) }
[2022-11-05T00:30:24Z DEBUG fvm_fuzz] Seed: 17879891932621801026
[2022-11-05T00:30:24Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(1) } }) }
[2022-11-05T00:30:24Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:30:35Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedbvmcemvfgntl5pbx6wf4exm3nrdp7qagk5bpls32qigiucknuzu

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==433== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0xaa,0x24,
\252$
artifact_prefix='./'; Test unit written to ./crash-53c8bb0235eeb7650ac49a6e48c405e6d6e04438
Base64: qiQ=
MERGE-OUTER: attempt 19
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1283530775
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/53c8bb0235eeb7650ac49a6e48c405e6d6e04438' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 18 processed earlier; will process 43 files now
[2022-11-05T00:30:35Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-6a2ffa3567b0d286348f4e6942d3e8e62d820d2a"
[2022-11-05T00:30:35Z DEBUG fvm_fuzz] Preseed 10
[2022-11-05T00:30:35Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:30:35Z DEBUG fvm_fuzz] Seed: 15262621999122172652
[2022-11-05T00:30:35Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:30:35Z DEBUG fvm_fuzz] Seed: 13477352567712729312
[2022-11-05T00:30:35Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:30:35Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:30:46Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzaced2ceh23j2mfvnuftyj6wvjsj5mxkjeuzqugmy5ii7nxycstrg6j6

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==436== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x5d,0xa,
]\012
artifact_prefix='./'; Test unit written to ./crash-de603c91038f329cce1cca8a30ea161b2271e2f6
Base64: XQo=
MERGE-OUTER: attempt 20
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1294902436
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/de603c91038f329cce1cca8a30ea161b2271e2f6' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 19 processed earlier; will process 42 files now
[2022-11-05T00:30:46Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/src"
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 21, kind: IsADirectory, message: "Is a directory" })', fuzz/fuzz_targets/execute.rs:34:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==439== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x90,0x90,
\220\220
artifact_prefix='./'; Test unit written to ./crash-bb4222750fa523fe0f63e33094efd56c2f66c40b
Base64: kJA=
MERGE-OUTER: attempt 21
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1294916182
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/bb4222750fa523fe0f63e33094efd56c2f66c40b' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 20 processed earlier; will process 41 files now
[2022-11-05T00:30:46Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-e9d94a0317e18d534e0b375b0af3d113017df8ff"
[2022-11-05T00:30:46Z DEBUG fvm_fuzz] Preseed 202
[2022-11-05T00:30:46Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:30:46Z DEBUG fvm_fuzz] Seed: 11013751472035877234
[2022-11-05T00:30:46Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(1) } }) }
[2022-11-05T00:30:46Z DEBUG fvm_fuzz] Seed: 11038072008787103322
[2022-11-05T00:30:46Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(1) } }) }
[2022-11-05T00:30:46Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:30:57Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacebmamuaigbrv5eyyolmjjycuqgn777kvyh442gse4ilefutloxbxi

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==442== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x3d,0xca,
=\312
artifact_prefix='./'; Test unit written to ./crash-77ea90badce22fff6c32e9b792410ae9fa9bf5cb
Base64: Pco=
MERGE-OUTER: attempt 22
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1306234898
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/77ea90badce22fff6c32e9b792410ae9fa9bf5cb' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 21 processed earlier; will process 40 files now
[2022-11-05T00:30:58Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-df23357e97906141e5e4306f67653ac87e817e3f"
[2022-11-05T00:30:58Z DEBUG fvm_fuzz] Preseed 4
[2022-11-05T00:30:58Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:30:58Z DEBUG fvm_fuzz] Seed: 18028995553505520188
[2022-11-05T00:30:58Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:30:58Z DEBUG fvm_fuzz] Seed: 13892003637693147589
[2022-11-05T00:30:58Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:30:58Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:31:09Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacebmwiv4nf4mkt5z4wgkff4aopfc5gcim7wvshgsot75lyw6sljvkc

Caused by:
    0: failed to validate actor wasm
    1: magic header not detected: bad magic number (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==445== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x2,0x4,
\002\004
artifact_prefix='./'; Test unit written to ./crash-4645c6afc0d8c65dad28bf8abeb39462d999dbf5
Base64: AgQ=
MERGE-OUTER: attempt 23
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1317578039
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/4645c6afc0d8c65dad28bf8abeb39462d999dbf5' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 22 processed earlier; will process 39 files now
[2022-11-05T00:31:09Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-a979ef10cc6f6a36df6b8a323307ee3bb2e2db9c"
[2022-11-05T00:31:09Z DEBUG fvm_fuzz] Preseed 32
[2022-11-05T00:31:09Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:31:09Z DEBUG fvm_fuzz] Seed: 9347598000121094869
[2022-11-05T00:31:09Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:31:09Z DEBUG fvm_fuzz] Seed: 7104677967032255628
[2022-11-05T00:31:09Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:31:09Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:31:20Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedazblmzflrgiaeckmrvzghdztonpdk5sx3u6ml7tsfpasbmwbfqw

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==448== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x0,0x20,
\000 
artifact_prefix='./'; Test unit written to ./crash-c9c6f959e838a460ca604781f6565ba32dabaad6
Base64: ACA=
MERGE-OUTER: attempt 24
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1328945973
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/c9c6f959e838a460ca604781f6565ba32dabaad6' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 23 processed earlier; will process 38 files now
[2022-11-05T00:31:20Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-4645c6afc0d8c65dad28bf8abeb39462d999dbf5"
[2022-11-05T00:31:20Z DEBUG fvm_fuzz] Preseed 42
[2022-11-05T00:31:20Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:31:20Z DEBUG fvm_fuzz] Seed: 5612343741886906158
[2022-11-05T00:31:20Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:31:20Z DEBUG fvm_fuzz] Seed: 5452211403613372577
[2022-11-05T00:31:20Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:31:20Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:31:31Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedd2jgzzzzplxt42ct7eo5dgwrphfd7fzc6vl74ar7d6gip2rp4fc

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==451== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x2a,0x2a,
**
artifact_prefix='./'; Test unit written to ./crash-bc2f74c22f98f7b6ffbc2f67453dbfa99bce9a32
Base64: Kio=
MERGE-OUTER: attempt 25
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1340344641
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/bc2f74c22f98f7b6ffbc2f67453dbfa99bce9a32' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 24 processed earlier; will process 37 files now
[2022-11-05T00:31:32Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-0ab8318acaf6e678dd02e2b5c343ed41111b393d"
[2022-11-05T00:31:32Z DEBUG fvm_fuzz] Preseed 128
[2022-11-05T00:31:32Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:31:32Z DEBUG fvm_fuzz] Seed: 11991420271000129962
[2022-11-05T00:31:32Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:31:32Z DEBUG fvm_fuzz] Seed: 14694383439169537343
[2022-11-05T00:31:32Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:31:32Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:31:43Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzaceabgrpu5xucen2vcc7q55shttesjgbpfkhl7yfbx3wcfeh3uvjrby

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==454== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x90,0x80,
\220\200
artifact_prefix='./'; Test unit written to ./crash-4fea4405f49ba4cd743f48268cd2b3cf29f659bb
Base64: kIA=
MERGE-OUTER: attempt 26
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1351783181
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/4fea4405f49ba4cd743f48268cd2b3cf29f659bb' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 25 processed earlier; will process 36 files now
[2022-11-05T00:31:43Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-356a192b7913b04c54574d18c28d46e6395428ab"
[2022-11-05T00:31:43Z DEBUG fvm_fuzz] Preseed 54
[2022-11-05T00:31:43Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:31:43Z DEBUG fvm_fuzz] Seed: 15433101762827047027
[2022-11-05T00:31:43Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:31:43Z DEBUG fvm_fuzz] Seed: 7735098977697820618
[2022-11-05T00:31:43Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:31:43Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:31:54Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacecjm35lyyryiljmzejlpbxhzpufrt4przhpe2x7dbq5m4ymrw3s5w

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==457== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0xdf,0x36,
\3376
artifact_prefix='./'; Test unit written to ./crash-3fad0efea1cf34fdd4e2aa6232e1cfb1103d5fd3
Base64: 3zY=
MERGE-OUTER: attempt 27
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1363138402
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/3fad0efea1cf34fdd4e2aa6232e1cfb1103d5fd3' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 26 processed earlier; will process 35 files now
[2022-11-05T00:31:55Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-902ba3cda1883801594b6e1b452790cc53948fda"
[2022-11-05T00:31:55Z DEBUG fvm_fuzz] Preseed 202
[2022-11-05T00:31:55Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:31:55Z DEBUG fvm_fuzz] Seed: 11013751472035877234
[2022-11-05T00:31:55Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:31:55Z DEBUG fvm_fuzz] Seed: 11038072008787103322
[2022-11-05T00:31:55Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:31:55Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:32:06Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzaceafeecyhftts62tignlw76tu5iq5zssm47aclw7opmo24r4mxjxss

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==460== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0xca,0xca,
\312\312
artifact_prefix='./'; Test unit written to ./crash-653dcfc7620fbf330005faec5a7417c9acb34a37
Base64: yso=
MERGE-OUTER: attempt 28
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1374471596
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/653dcfc7620fbf330005faec5a7417c9acb34a37' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 27 processed earlier; will process 34 files now
[2022-11-05T00:32:06Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-9b53a457f97015385d639ece8932cdeea63256db"
[2022-11-05T00:32:06Z DEBUG fvm_fuzz] Preseed 36
[2022-11-05T00:32:06Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:32:06Z DEBUG fvm_fuzz] Seed: 8233762969215426441
[2022-11-05T00:32:06Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:32:06Z DEBUG fvm_fuzz] Seed: 17879891932621801026
[2022-11-05T00:32:06Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:32:06Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:32:17Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzaceb2zxp2j72apo3ivyu243ioukgzphlx2aq377vscssbxgqkta4zg2

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==463== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x32,0x24,
2$
artifact_prefix='./'; Test unit written to ./crash-8d4fd74a74e06571bd19f242e3049badbe9f6980
Base64: MiQ=
MERGE-OUTER: attempt 29
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1385814196
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/8d4fd74a74e06571bd19f242e3049badbe9f6980' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 28 processed earlier; will process 33 files now
[2022-11-05T00:32:17Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-fb96549631c835eb239cd614cc6b5cb7d295121a"
[2022-11-05T00:32:17Z DEBUG fvm_fuzz] Preseed 50
[2022-11-05T00:32:17Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:32:17Z DEBUG fvm_fuzz] Seed: 12228161294529759991
[2022-11-05T00:32:17Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:32:17Z DEBUG fvm_fuzz] Seed: 8086395473974376476
[2022-11-05T00:32:17Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:32:17Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:32:28Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedf4mpocvs4gxweworj67gh5j4v6f4tnom32be3zlaqryeukdc2ee

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==466== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x8a,0x32,
\2122
artifact_prefix='./'; Test unit written to ./crash-af264967730e276acaf9b0c72cd1e526dcb8eda8
Base64: ijI=
MERGE-OUTER: attempt 30
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1397247891
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/af264967730e276acaf9b0c72cd1e526dcb8eda8' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 29 processed earlier; will process 32 files now
[2022-11-05T00:32:29Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-902ba3cda1883801594b6e1b452790cc53948fda"
[2022-11-05T00:32:29Z DEBUG fvm_fuzz] Preseed 138
[2022-11-05T00:32:29Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:32:29Z DEBUG fvm_fuzz] Seed: 10913798493422644034
[2022-11-05T00:32:29Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:32:29Z DEBUG fvm_fuzz] Seed: 9845055533535579289
[2022-11-05T00:32:29Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:32:29Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:32:40Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzaceafeecyhftts62tignlw76tu5iq5zssm47aclw7opmo24r4mxjxss

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==469== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x8a,0x8a,
\212\212
artifact_prefix='./'; Test unit written to ./crash-357b645c7e8edc8dbe63675d2908c3d42e071b3a
Base64: ioo=
MERGE-OUTER: attempt 31
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1408642511
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/357b645c7e8edc8dbe63675d2908c3d42e071b3a' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 30 processed earlier; will process 31 files now
[2022-11-05T00:32:40Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-805fd18ce66818429d4225f114eb391d84c3c9b2"
[2022-11-05T00:32:40Z DEBUG fvm_fuzz] Preseed 0
[2022-11-05T00:32:40Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:32:40Z DEBUG fvm_fuzz] Seed: 8100708189767581495
[2022-11-05T00:32:40Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:32:40Z DEBUG fvm_fuzz] Seed: 18075600217600495122
[2022-11-05T00:32:40Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:32:40Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:32:51Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzaced5oukxz6cwkitfixxmzhnhubtyvhpxjrhzpo6bbuulzh3qefs3ae

Caused by:
    0: failed to validate actor wasm
    1: magic header not detected: bad magic number (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==472== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x2,0x0,
\002\000
artifact_prefix='./'; Test unit written to ./crash-9b99593353a610c4bee0d6a94a01a3296080c0fb
Base64: AgA=
MERGE-OUTER: attempt 32
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1420003938
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/9b99593353a610c4bee0d6a94a01a3296080c0fb' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 31 processed earlier; will process 30 files now
[2022-11-05T00:32:52Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-2830db7726582010627cc5481329b73487cf9e91"
[2022-11-05T00:32:52Z DEBUG fvm_fuzz] Preseed 36
[2022-11-05T00:32:52Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:32:52Z DEBUG fvm_fuzz] Seed: 8233762969215426441
[2022-11-05T00:32:52Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:32:52Z DEBUG fvm_fuzz] Seed: 17879891932621801026
[2022-11-05T00:32:52Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:32:52Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:33:02Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacecre7og7qruvyupldmgtfrugihznik2xq4ntupuwobv5kwbe2slfe

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==475== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x33,0x24,
3$
artifact_prefix='./'; Test unit written to ./crash-a473a4cbe433c0c6b88040868d854e31bf30f273
Base64: MyQ=
MERGE-OUTER: attempt 33
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1431346802
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/a473a4cbe433c0c6b88040868d854e31bf30f273' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 32 processed earlier; will process 29 files now
[2022-11-05T00:33:03Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-8d38a3be8d3be66148d5f9c7d436e943f5670a43"
[2022-11-05T00:33:03Z DEBUG fvm_fuzz] Preseed 177
[2022-11-05T00:33:03Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:33:03Z DEBUG fvm_fuzz] Seed: 4165632434108329730
[2022-11-05T00:33:03Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(1) } }) }
[2022-11-05T00:33:03Z DEBUG fvm_fuzz] Seed: 7088914466750956530
[2022-11-05T00:33:03Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(1) } }) }
[2022-11-05T00:33:03Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:33:14Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacecivrjz7p3byx42ulhw5oclf7gf2pivimqh6besbptgp4go6uyade

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==478== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x8a,0xb1,
\212\261
artifact_prefix='./'; Test unit written to ./crash-94c3c5fd1ed8ec83b0a6ebc4f1db31ac68939594
Base64: irE=
MERGE-OUTER: attempt 34
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1442705094
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/94c3c5fd1ed8ec83b0a6ebc4f1db31ac68939594' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 33 processed earlier; will process 28 files now
[2022-11-05T00:33:14Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-a979ef10cc6f6a36df6b8a323307ee3bb2e2db9c"
[2022-11-05T00:33:14Z DEBUG fvm_fuzz] Preseed 45258
[2022-11-05T00:33:14Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:33:14Z DEBUG fvm_fuzz] Seed: 15730529427444375330
[2022-11-05T00:33:14Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:33:14Z DEBUG fvm_fuzz] Seed: 12635027955738590434
[2022-11-05T00:33:14Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:33:14Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:33:25Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedazblmzflrgiaeckmrvzghdztonpdk5sx3u6ml7tsfpasbmwbfqw

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==481== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x0,0xca,0xb0,
\000\312\260
artifact_prefix='./'; Test unit written to ./crash-7da59895b37d7d151e2be8ecf0d7970e2263a724
Base64: AMqw
MERGE-OUTER: attempt 35
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1454048100
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/7da59895b37d7d151e2be8ecf0d7970e2263a724' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 34 processed earlier; will process 27 files now
[2022-11-05T00:33:26Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-9842926af7ca0a8cca12604f945414f07b01e13d"
[2022-11-05T00:33:26Z DEBUG fvm_fuzz] Preseed 9778
[2022-11-05T00:33:26Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:33:26Z DEBUG fvm_fuzz] Seed: 12257871700422806731
[2022-11-05T00:33:26Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:33:26Z DEBUG fvm_fuzz] Seed: 15269208487964031000
[2022-11-05T00:33:26Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:33:26Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:33:36Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzaceduixv2xvvnzx3ptolmnh4gpnslcuru5wyncmx3eddq773mg3iu6y

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==484== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x8a,0x32,0x26,
\2122&
artifact_prefix='./'; Test unit written to ./crash-16a776716695da01265c361b31f8388fb9ba2c9f
Base64: ijIm
MERGE-OUTER: attempt 36
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1465396699
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/16a776716695da01265c361b31f8388fb9ba2c9f' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 35 processed earlier; will process 26 files now
[2022-11-05T00:33:37Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-ca6792a9b1b7c4599aa2be9393aaea8c9c9d6bcf"
[2022-11-05T00:33:37Z DEBUG fvm_fuzz] Preseed 12288
[2022-11-05T00:33:37Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:33:37Z DEBUG fvm_fuzz] Seed: 12885370453030938686
[2022-11-05T00:33:37Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:33:37Z DEBUG fvm_fuzz] Seed: 875379450857601068
[2022-11-05T00:33:37Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:33:37Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:33:48Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedzmcdg4zpkchbwuvwn6sh72zkuezksshyaukqbl4amf3fjeyfucw

Caused by:
    0: failed to validate actor wasm
    1: magic header not detected: bad magic number (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==487== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0xca,0x0,0x30,
\312\0000
artifact_prefix='./'; Test unit written to ./crash-570e953a5a28346ac202d790ac9d8f91323c1b4d
Base64: ygAw
MERGE-OUTER: attempt 37
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1476768608
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/570e953a5a28346ac202d790ac9d8f91323c1b4d' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 36 processed earlier; will process 25 files now
[2022-11-05T00:33:48Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-94c3c5fd1ed8ec83b0a6ebc4f1db31ac68939594"
[2022-11-05T00:33:48Z DEBUG fvm_fuzz] Preseed 8192
[2022-11-05T00:33:48Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:33:48Z DEBUG fvm_fuzz] Seed: 8067503222160601185
[2022-11-05T00:33:48Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:33:48Z DEBUG fvm_fuzz] Seed: 11918531535824658206
[2022-11-05T00:33:48Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:33:48Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:33:59Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzaceaj7kb6bal33qqoczxcrczmk3gpr5zhgbm4fedmebtw2ttuadaots

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==490== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0xca,0x0,0x20,
\312\000 
artifact_prefix='./'; Test unit written to ./crash-624c0ad1c7e9c7ae46a339fd7fe1194b8649fd12
Base64: ygAg
MERGE-OUTER: attempt 38
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1488141871
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/624c0ad1c7e9c7ae46a339fd7fe1194b8649fd12' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 37 processed earlier; will process 24 files now
[2022-11-05T00:34:00Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/wasms"
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 21, kind: IsADirectory, message: "Is a directory" })', fuzz/fuzz_targets/execute.rs:34:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==493== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x90,0x32,0x80,
\2202\200
artifact_prefix='./'; Test unit written to ./crash-722a7c72fd22ec4a976d6c30858c7253178d4e65
Base64: kDKA
MERGE-OUTER: attempt 39
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1488154721
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/722a7c72fd22ec4a976d6c30858c7253178d4e65' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 38 processed earlier; will process 23 files now
[2022-11-05T00:34:00Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-0ab8318acaf6e678dd02e2b5c343ed41111b393d"
[2022-11-05T00:34:00Z DEBUG fvm_fuzz] Preseed 12490
[2022-11-05T00:34:00Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:34:00Z DEBUG fvm_fuzz] Seed: 14703257772462261760
[2022-11-05T00:34:00Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:34:00Z DEBUG fvm_fuzz] Seed: 6266932195614492028
[2022-11-05T00:34:00Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:34:00Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:34:11Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzaceabgrpu5xucen2vcc7q55shttesjgbpfkhl7yfbx3wcfeh3uvjrby

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==496== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x5d,0xca,0x30,
]\3120
artifact_prefix='./'; Test unit written to ./crash-8c6ac4f7e77ca06ee050df0be09d3730efb9b42a
Base64: Xcow
MERGE-OUTER: attempt 40
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1499472480
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/8c6ac4f7e77ca06ee050df0be09d3730efb9b42a' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 39 processed earlier; will process 22 files now
[2022-11-05T00:34:11Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-a979ef10cc6f6a36df6b8a323307ee3bb2e2db9c"
[2022-11-05T00:34:11Z DEBUG fvm_fuzz] Preseed 12490
[2022-11-05T00:34:11Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:34:11Z DEBUG fvm_fuzz] Seed: 14703257772462261760
[2022-11-05T00:34:11Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:34:11Z DEBUG fvm_fuzz] Seed: 6266932195614492028
[2022-11-05T00:34:11Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:34:11Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:34:22Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedazblmzflrgiaeckmrvzghdztonpdk5sx3u6ml7tsfpasbmwbfqw

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==499== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x0,0xca,0x30,
\000\3120
artifact_prefix='./'; Test unit written to ./crash-95b9d458940ccaf81374d902e66562f61f155ccf
Base64: AMow
MERGE-OUTER: attempt 41
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1510850357
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/95b9d458940ccaf81374d902e66562f61f155ccf' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 40 processed earlier; will process 21 files now
[2022-11-05T00:34:22Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-570e953a5a28346ac202d790ac9d8f91323c1b4d"
[2022-11-05T00:34:22Z DEBUG fvm_fuzz] Preseed 2367488
[2022-11-05T00:34:22Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:34:22Z DEBUG fvm_fuzz] Seed: 13091988255323749924
[2022-11-05T00:34:22Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(1) } }) }
[2022-11-05T00:34:22Z DEBUG fvm_fuzz] Seed: 17031997410692313852
[2022-11-05T00:34:22Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(1) } }) }
[2022-11-05T00:34:22Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:34:33Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacea22y4m7myweauenzlwxep52yrp7q6i53djslrb2zxntd3x6xczts

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==502== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x33,0x0,0x20,0x24,
3\000 $
artifact_prefix='./'; Test unit written to ./crash-3d38e933f221b921ad62c497fe2f0e9606204abf
Base64: MwAgJA==
MERGE-OUTER: attempt 42
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1522241242
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/3d38e933f221b921ad62c497fe2f0e9606204abf' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 41 processed earlier; will process 20 files now
[2022-11-05T00:34:34Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-df58248c414f342c81e056b40bee12d17a08bf61"
[2022-11-05T00:34:34Z DEBUG fvm_fuzz] Preseed 2411255
[2022-11-05T00:34:34Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:34:34Z DEBUG fvm_fuzz] Seed: 9370551159729011295
[2022-11-05T00:34:34Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:34:34Z DEBUG fvm_fuzz] Seed: 13288677717650681555
[2022-11-05T00:34:34Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:34:34Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:34:45Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacea4vuerowfacx4sw3bxd7jchmthzvtcvsal2aczlt3qsjghhh3zlk

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==505== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x33,0xf7,0xca,0x24,
3\367\312$
artifact_prefix='./'; Test unit written to ./crash-361c2cc6c4f2920245dddf94e6df9d07d402729b
Base64: M/fKJA==
MERGE-OUTER: attempt 43
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1533578744
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/361c2cc6c4f2920245dddf94e6df9d07d402729b' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 42 processed earlier; will process 19 files now
[2022-11-05T00:34:45Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-df58248c414f342c81e056b40bee12d17a08bf61"
[2022-11-05T00:34:45Z DEBUG fvm_fuzz] Preseed 2411008
[2022-11-05T00:34:45Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:34:45Z DEBUG fvm_fuzz] Seed: 18049144092873269299
[2022-11-05T00:34:45Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:34:45Z DEBUG fvm_fuzz] Seed: 1026785648090855062
[2022-11-05T00:34:45Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:34:45Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:34:56Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacea4vuerowfacx4sw3bxd7jchmthzvtcvsal2aczlt3qsjghhh3zlk

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==508== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x33,0x0,0xca,0x24,
3\000\312$
artifact_prefix='./'; Test unit written to ./crash-d1666a043b67bc10b05e87a4b279726edd9305b6
Base64: MwDKJA==
MERGE-OUTER: attempt 44
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1544929003
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/d1666a043b67bc10b05e87a4b279726edd9305b6' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 43 processed earlier; will process 18 files now
[2022-11-05T00:34:56Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-0fcb72a1d846a2b3ccaac57838c3cd0b4a296f52"
[2022-11-05T00:34:56Z DEBUG fvm_fuzz] Preseed 4294967295
[2022-11-05T00:34:56Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:34:56Z DEBUG fvm_fuzz] Seed: 563399432482698358
[2022-11-05T00:34:56Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:34:56Z DEBUG fvm_fuzz] Seed: 5334838740728709497
[2022-11-05T00:34:56Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:34:56Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:35:07Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzaceafcgxz4lcctwiabjok5r3jffos2ws24wtinxxsgnfxpvoe3rptnq

Caused by:
    0: failed to validate actor wasm
    1: magic header not detected: bad magic number (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==511== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x37,0xff,0xff,0xff,0xff,
7\377\377\377\377
artifact_prefix='./'; Test unit written to ./crash-5b40223abe60026179c443198cd1f5ce67f86c9b
Base64: N/////8=
MERGE-OUTER: attempt 45
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1556287280
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/5b40223abe60026179c443198cd1f5ce67f86c9b' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 44 processed earlier; will process 17 files now
[2022-11-05T00:35:08Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-a979ef10cc6f6a36df6b8a323307ee3bb2e2db9c"
[2022-11-05T00:35:08Z DEBUG fvm_fuzz] Preseed 2966036480
[2022-11-05T00:35:08Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:35:08Z DEBUG fvm_fuzz] Seed: 7448536045723885371
[2022-11-05T00:35:08Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:35:08Z DEBUG fvm_fuzz] Seed: 5235275077372499914
[2022-11-05T00:35:08Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:35:08Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:35:19Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedazblmzflrgiaeckmrvzghdztonpdk5sx3u6ml7tsfpasbmwbfqw

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==514== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x0,0x0,0x20,0xca,0xb0,
\000\000 \312\260
artifact_prefix='./'; Test unit written to ./crash-874219b829e49062c7fd5d9da86e89ae315e4832
Base64: AAAgyrA=
MERGE-OUTER: attempt 46
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1567642119
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/874219b829e49062c7fd5d9da86e89ae315e4832' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 45 processed earlier; will process 16 files now
[2022-11-05T00:35:19Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-874219b829e49062c7fd5d9da86e89ae315e4832"
[2022-11-05T00:35:19Z DEBUG fvm_fuzz] Preseed 18446744073709551488
[2022-11-05T00:35:19Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:35:19Z DEBUG fvm_fuzz] Seed: 5646601972984538855
[2022-11-05T00:35:19Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:35:19Z DEBUG fvm_fuzz] Seed: 6246174901893262673
[2022-11-05T00:35:19Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:35:19Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:35:30Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedi2ayrrf7nw4y7k3f3hqzug7udvd7tcj7sdqrvmbhmnr6fabpswg

Caused by:
    0: failed to validate actor wasm
    1: magic header not detected: bad magic number (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==517== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x90,0x80,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x1c,
\220\200\377\377\377\377\377\377\377\034
artifact_prefix='./'; Test unit written to ./crash-c3c3c59a7c86cdb6389c314418b9f85d0dd83884
Base64: kID/////////HA==
MERGE-OUTER: attempt 47
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1578992589
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/c3c3c59a7c86cdb6389c314418b9f85d0dd83884' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 46 processed earlier; will process 15 files now
[2022-11-05T00:35:31Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-dd321f172f6b0c132abb9f93bce6573658279ab1"
[2022-11-05T00:35:31Z DEBUG fvm_fuzz] Preseed 9952110751558664191
[2022-11-05T00:35:31Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:35:31Z DEBUG fvm_fuzz] Seed: 15097761690447272583
[2022-11-05T00:35:31Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:35:31Z DEBUG fvm_fuzz] Seed: 15619661092195981417
[2022-11-05T00:35:31Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:35:31Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:35:41Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzaceapzpnfoqwsih5422aq5nq2ngh65xbze7cr26iow6zrk37akmwtbo

Caused by:
    0: failed to validate actor wasm
    1: magic header not detected: bad magic number (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==520== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x1c,0x8a,0x32,
\377\377\377\377\377\377\377\034\2122
artifact_prefix='./'; Test unit written to ./crash-cde7e752fc1feb9b0f13e2649d700c886bcf007a
Base64: /////////xyKMg==
MERGE-OUTER: attempt 48
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1590359506
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/cde7e752fc1feb9b0f13e2649d700c886bcf007a' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 47 processed earlier; will process 14 files now
[2022-11-05T00:35:42Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-805fd18ce66818429d4225f114eb391d84c3c9b2"
[2022-11-05T00:35:42Z DEBUG fvm_fuzz] Preseed 10961382076765110730
[2022-11-05T00:35:42Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:35:42Z DEBUG fvm_fuzz] Seed: 11736717223023012655
[2022-11-05T00:35:42Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:35:42Z DEBUG fvm_fuzz] Seed: 10761926451827413047
[2022-11-05T00:35:42Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:35:42Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:35:53Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzaced5oukxz6cwkitfixxmzhnhubtyvhpxjrhzpo6bbuulzh3qefs3ae

Caused by:
    0: failed to validate actor wasm
    1: magic header not detected: bad magic number (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==523== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x5d,0xca,0x1,0xeb,0x44,0xec,0xa6,0x1e,0x98,0xe0,0xe3,0x8b,0xc6,0x36,0x99,0xde,0xbc,0xf,0x50,0x2a,0xa0,0xb1,0x83,0x30,
]\312\001\353D\354\246\036\230\340\343\213\3066\231\336\274\017P*\240\261\2030
artifact_prefix='./'; Test unit written to ./crash-b6348d23919a83f79face1af1166e596b174988d
Base64: XcoB60Tsph6Y4OOLxjaZ3rwPUCqgsYMw
MERGE-OUTER: attempt 49
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1601686171
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/b6348d23919a83f79face1af1166e596b174988d' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 48 processed earlier; will process 13 files now
[2022-11-05T00:35:53Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-cde7e752fc1feb9b0f13e2649d700c886bcf007a"
[2022-11-05T00:35:53Z DEBUG fvm_fuzz] Preseed 12876550765177647794
[2022-11-05T00:35:53Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:35:53Z DEBUG fvm_fuzz] Seed: 16638271252824601755
[2022-11-05T00:35:53Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:35:53Z DEBUG fvm_fuzz] Seed: 11278584869387483927
[2022-11-05T00:35:53Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:35:53Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:36:04Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedvfmaj2vwrcqtqxgnvhpmrpq2yghw4qsnn3zurli4v6whj56yqt6

Caused by:
    0: failed to validate actor wasm
    1: magic header not detected: bad magic number (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==526== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xb2,0xca,
\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\262\312
artifact_prefix='./'; Test unit written to ./crash-b9e923040f207571d73957c2e3ae1d549439f808
Base64: srKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKyyg==
MERGE-OUTER: attempt 50
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1613032624
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/b9e923040f207571d73957c2e3ae1d549439f808' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 49 processed earlier; will process 12 files now
[2022-11-05T00:36:05Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-3c89586d99f2567d21410f29b1b2606574892aa7"
[2022-11-05T00:36:05Z DEBUG fvm_fuzz] Preseed 12587190073825341102
[2022-11-05T00:36:05Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:36:05Z DEBUG fvm_fuzz] Seed: 17828705714409792408
[2022-11-05T00:36:05Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:36:05Z DEBUG fvm_fuzz] Seed: 639463620803904939
[2022-11-05T00:36:05Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:36:05Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:36:15Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedtpzrlzhx5tvlvgizkwqiksu76e3ne3z6w6mfirdi4vquo6t2rce

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==529== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0x4a,
\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256J
artifact_prefix='./'; Test unit written to ./crash-8acb399f30a2b4af09e5527855455baacb17ea46
Base64: rq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urko=
MERGE-OUTER: attempt 51
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1624391421
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/8acb399f30a2b4af09e5527855455baacb17ea46' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 50 processed earlier; will process 11 files now
[2022-11-05T00:36:16Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-c4e0186e2fc7beb6d7a7245648ed43340d313afe"
[2022-11-05T00:36:16Z DEBUG fvm_fuzz] Preseed 6655295901103053916
[2022-11-05T00:36:16Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:36:16Z DEBUG fvm_fuzz] Seed: 5297239820612694177
[2022-11-05T00:36:16Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:36:16Z DEBUG fvm_fuzz] Seed: 15556120729907974678
[2022-11-05T00:36:16Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:36:16Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:36:27Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzaceammqiclh4ixdxzmz5bfwgkapzrj3nsratlwvherelrnz2pdjnhqm

Caused by:
    0: failed to validate actor wasm
    1: magic header not detected: bad magic number (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==532== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x0,0x20,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x2a,
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\000 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*
artifact_prefix='./'; Test unit written to ./crash-351d8211e3ce8ea1039a14df6c310a740d1f5e08
Base64: XFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFwAIFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFwq
MERGE-OUTER: attempt 52
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1635704864
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/351d8211e3ce8ea1039a14df6c310a740d1f5e08' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 51 processed earlier; will process 10 files now
[2022-11-05T00:36:27Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-361c2cc6c4f2920245dddf94e6df9d07d402729b"
[2022-11-05T00:36:27Z DEBUG fvm_fuzz] Preseed 12587190073825341102
[2022-11-05T00:36:27Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:36:27Z DEBUG fvm_fuzz] Seed: 17828705714409792408
[2022-11-05T00:36:27Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:36:27Z DEBUG fvm_fuzz] Seed: 639463620803904939
[2022-11-05T00:36:27Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:36:27Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:36:38Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacebsqa65t26nsqjj2koblgsanc3sltmgzmg637hywviry4rhztpgck

Caused by:
    0: failed to validate actor wasm
    1: magic header not detected: bad magic number (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==535== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0x29,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0xae,0x4a,
\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256)\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256\256J
artifact_prefix='./'; Test unit written to ./crash-4ff0408ee9dd23962048ca6d2a91a3d1207aec84
Base64: rq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6uKa6urq6urq6urq6urq6urq6urq6urq6urq6urq5K
MERGE-OUTER: attempt 53
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1647023152
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/4ff0408ee9dd23962048ca6d2a91a3d1207aec84' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 52 processed earlier; will process 9 files now
[2022-11-05T00:36:39Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-a979ef10cc6f6a36df6b8a323307ee3bb2e2db9c"
[2022-11-05T00:36:39Z DEBUG fvm_fuzz] Preseed 0
[2022-11-05T00:36:39Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:36:39Z DEBUG fvm_fuzz] Seed: 8100708189767581495
[2022-11-05T00:36:39Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:36:39Z DEBUG fvm_fuzz] Seed: 18075600217600495122
[2022-11-05T00:36:39Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:36:39Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:36:49Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedazblmzflrgiaeckmrvzghdztonpdk5sx3u6ml7tsfpasbmwbfqw

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==538== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x25,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x8a,0x32,
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000%\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\2122
artifact_prefix='./'; Test unit written to ./crash-9a25f74d95b4755c7b680b7803c0b956ba74c59c
Base64: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKMg==
MERGE-OUTER: attempt 54
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1658382372
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/9a25f74d95b4755c7b680b7803c0b956ba74c59c' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 53 processed earlier; will process 8 files now
[2022-11-05T00:36:50Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-a979ef10cc6f6a36df6b8a323307ee3bb2e2db9c"
[2022-11-05T00:36:50Z DEBUG fvm_fuzz] Preseed 0
[2022-11-05T00:36:50Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:36:50Z DEBUG fvm_fuzz] Seed: 8100708189767581495
[2022-11-05T00:36:50Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:36:50Z DEBUG fvm_fuzz] Seed: 18075600217600495122
[2022-11-05T00:36:50Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:36:50Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:37:01Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedazblmzflrgiaeckmrvzghdztonpdk5sx3u6ml7tsfpasbmwbfqw

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==541== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x8a,0x32,
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\2122
artifact_prefix='./'; Test unit written to ./crash-5492e618dd00b55f7e0c64b82ed6792918729bd9
Base64: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKMg==
MERGE-OUTER: attempt 55
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1669736919
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/5492e618dd00b55f7e0c64b82ed6792918729bd9' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 54 processed earlier; will process 7 files now
[2022-11-05T00:37:01Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-a979ef10cc6f6a36df6b8a323307ee3bb2e2db9c"
[2022-11-05T00:37:01Z DEBUG fvm_fuzz] Preseed 0
[2022-11-05T00:37:01Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:37:01Z DEBUG fvm_fuzz] Seed: 8100708189767581495
[2022-11-05T00:37:01Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:37:01Z DEBUG fvm_fuzz] Seed: 18075600217600495122
[2022-11-05T00:37:01Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:37:01Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:37:12Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedazblmzflrgiaeckmrvzghdztonpdk5sx3u6ml7tsfpasbmwbfqw

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==544== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x4a,
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000J
artifact_prefix='./'; Test unit written to ./crash-e0038e116af1a253b62adbd821e7e99cfd2850fe
Base64: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASg==
MERGE-OUTER: attempt 56
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1681078347
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/e0038e116af1a253b62adbd821e7e99cfd2850fe' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 55 processed earlier; will process 6 files now
[2022-11-05T00:37:13Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-d1666a043b67bc10b05e87a4b279726edd9305b6"
[2022-11-05T00:37:13Z DEBUG fvm_fuzz] Preseed 8753160913407277433
[2022-11-05T00:37:13Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:37:13Z DEBUG fvm_fuzz] Seed: 7565960798897220211
[2022-11-05T00:37:13Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:37:13Z DEBUG fvm_fuzz] Seed: 17727082580112375813
[2022-11-05T00:37:13Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:37:13Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:37:23Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzaceaf3mwna67czdswqtvhv5lg5xiscpguonjlur5xftaehkytrndbfc

Caused by:
    0: failed to validate actor wasm
    1: magic header not detected: bad magic number (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==547== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x36,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,0x79,
6yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
artifact_prefix='./'; Test unit written to ./crash-8c55b9e3c58fbaa31872268e4df71b7bac954e50
Base64: Nnl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eQ==
MERGE-OUTER: attempt 57
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1692420867
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/8c55b9e3c58fbaa31872268e4df71b7bac954e50' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 56 processed earlier; will process 5 files now
[2022-11-05T00:37:24Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-7219e685eebe2b43caf431c16ba90a1f6ffc0b16"
[2022-11-05T00:37:24Z DEBUG fvm_fuzz] Preseed 6655295901103053916
[2022-11-05T00:37:24Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:37:24Z DEBUG fvm_fuzz] Seed: 5297239820612694177
[2022-11-05T00:37:24Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:37:24Z DEBUG fvm_fuzz] Seed: 15556120729907974678
[2022-11-05T00:37:24Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "magic header not detected: bad magic number", offset: 0, needed_hint: None } }) }
[2022-11-05T00:37:24Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:37:35Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacecporvtv5gsbjdgs4wllb2h6fwqdjf4lltbknescr2bh77evts6y2

Caused by:
    0: failed to validate actor wasm
    1: magic header not detected: bad magic number (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==550== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x0,0x20,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x0,0x20,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x2a,
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\000 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\000 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*
artifact_prefix='./'; Test unit written to ./crash-21fe5dd8164394c429f2943b37f3644e0f6579ec
Base64: XFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFwAIFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFwAIFxcXFxcXFxcXFxcXFxcXFxcKg==
MERGE-OUTER: attempt 58
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1703716862
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/21fe5dd8164394c429f2943b37f3644e0f6579ec' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 57 processed earlier; will process 4 files now
[2022-11-05T00:37:35Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-624c0ad1c7e9c7ae46a339fd7fe1194b8649fd12"
[2022-11-05T00:37:35Z DEBUG fvm_fuzz] Preseed 6655295901103053916
[2022-11-05T00:37:35Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:37:35Z DEBUG fvm_fuzz] Seed: 5297239820612694177
[2022-11-05T00:37:35Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(1) } }) }
[2022-11-05T00:37:35Z DEBUG fvm_fuzz] Seed: 15556120729907974678
[2022-11-05T00:37:35Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(1) } }) }
[2022-11-05T00:37:35Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:37:46Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedrfnxn223oog3ptb5ivmxbc4uo7uh5zkgbhwkmczv4k42isutxqo

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==553== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x0,0x20,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x2a,
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\000 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*
artifact_prefix='./'; Test unit written to ./crash-10d3c11c5b88cd43dff296d43f1d7b470291bc20
Base64: XFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFwAIFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcKg==
MERGE-OUTER: attempt 59
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1715120697
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/10d3c11c5b88cd43dff296d43f1d7b470291bc20' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 58 processed earlier; will process 3 files now
[2022-11-05T00:37:47Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-fb96549631c835eb239cd614cc6b5cb7d295121a"
[2022-11-05T00:37:47Z DEBUG fvm_fuzz] Preseed 6655295901103053916
[2022-11-05T00:37:47Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:37:47Z DEBUG fvm_fuzz] Seed: 5297239820612694177
[2022-11-05T00:37:47Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:37:47Z DEBUG fvm_fuzz] Seed: 15556120729907974678
[2022-11-05T00:37:47Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(2) } }) }
[2022-11-05T00:37:47Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:37:57Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedf4mpocvs4gxweworj67gh5j4v6f4tnom32be3zlaqryeukdc2ee

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==556== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x2a,
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*
artifact_prefix='./'; Test unit written to ./crash-6c0602c8c93c5f20b908ba26d94aa6c223bd3efe
Base64: XFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcKg==
MERGE-OUTER: attempt 60
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1726422954
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/6c0602c8c93c5f20b908ba26d94aa6c223bd3efe' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 59 processed earlier; will process 2 files now
[2022-11-05T00:37:58Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-c4488af0c158e8c2832cb927cfb3ce534104cd1e"
[2022-11-05T00:37:58Z DEBUG fvm_fuzz] Preseed 6655295901103053916
[2022-11-05T00:37:58Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:37:58Z DEBUG fvm_fuzz] Seed: 5297239820612694177
[2022-11-05T00:37:58Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:37:58Z DEBUG fvm_fuzz] Seed: 15556120729907974678
[2022-11-05T00:37:58Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:37:58Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:38:09Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedjzusjj5scmjixg5nztmnf2ucsuwdjfkv4dtrgaalyuynggk6dmo

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==559== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0xb8,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x2a,
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\270\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*
artifact_prefix='./'; Test unit written to ./crash-dd486a08974368137e0f56899e24d71004406542
Base64: XFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcuFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXCo=
MERGE-OUTER: attempt 61
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1737764683
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge188.txt'
MERGE-INNER: '/github/workspace/cifuzz-corpus/execute/dd486a08974368137e0f56899e24d71004406542' caused a failure at the previous merge step
MERGE-INNER: 61 total files; 60 processed earlier; will process 1 files now
[2022-11-05T00:38:09Z DEBUG fvm_fuzz] Random fixture: "/github/workspace/build-out/crash-c4488af0c158e8c2832cb927cfb3ce534104cd1e"
[2022-11-05T00:38:09Z DEBUG fvm_fuzz] Preseed 6655295901103053916
[2022-11-05T00:38:09Z DEBUG fvm_fuzz] stacked_mutations: 1
[2022-11-05T00:38:09Z DEBUG fvm_fuzz] Seed: 5297239820612694177
[2022-11-05T00:38:09Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:38:09Z DEBUG fvm_fuzz] Seed: 15556120729907974678
[2022-11-05T00:38:09Z DEBUG fvm_fuzz] Error: Error { kind: Parse(BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 0, needed_hint: Some(3) } }) }
[2022-11-05T00:38:09Z DEBUG fvm_fuzz] Executing 50 times
[2022-11-05T00:38:20Z DEBUG fvm_fuzz] Instantiating machine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: could not prepare actor with code CID bafk2bzacedjzusjj5scmjixg5nztmnf2ucsuwdjfkv4dtrgaalyuynggk6dmo

Caused by:
    0: failed to validate actor wasm
    1: unexpected end-of-file (at offset 0x0)', fuzz/src/lib.rs:189:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==562== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x0,0x20,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x5c,0x2a,
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\000 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*
artifact_prefix='./'; Test unit written to ./crash-9186bd3cc5806f265218895d791437bd550006e0
Base64: XFxcXFxcXFxcXFxcXFxcXFxcXFxcXFwAIFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFwq
MERGE-OUTER: the control file has 5751 bytes
MERGE-OUTER: consumed 0Mb (31Mb rss) to parse the control file
MERGE-OUTER: 0 new files with 0 new features added; 0 new coverage edges
